GET http://localhost:8080/boards 

###
POST http://localhost:8080/boards/post 
Content-Type: application/json;charset=UTF-8

{
    "writer": "ww",
    "title": "test",
    "content": "testtest",
    "readcount": "0",
    "istemp": false
}
###


PUT http://localhost:8080/boards/edit/7
Content-Type: application/json;charset=UTF-8

{
    "num": "7",
    "writer": "ww",
    "title": "update",
    "content": "testtest",
    "readcount": "0",
    "istemp": false
}
###
DELETE http://localhost:8080/boards/delete/6

###
GET http://localhost:8080/boards/detail/1

###